2019-07-09 11:02:03,233 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-09 11:04:46,291 ERROR: Exception on /edit_profile [POST] [in /home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/thevidvid/microblog/app/routes.py", line 104, in edit_profile
    db.session.commit()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
    raise value
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/thevidvid/microblog/mb_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('thevidvid', 'I am a professional interior designer living in Southern Califonia. Owner of Avid Design studio.\r\n', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-07-09 11:34:26,975 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-09 15:38:24,921 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-09 15:38:38,632 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-09 16:00:39,115 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-09 19:30:42,313 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-28 13:26:09,584 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-28 13:26:24,488 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:51]
2019-07-29 12:50:36,675 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-07-29 15:05:25,763 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-07-29 15:06:46,974 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-07-29 15:07:07,064 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-07 23:44:58,182 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-07 23:59:09,401 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-08 00:01:23,118 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-08 01:03:10,426 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-08 01:13:42,731 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-08 21:14:26,970 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-08 21:14:34,337 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-11 23:59:59,265 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-12 14:38:10,442 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-12 14:38:29,483 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-13 12:04:00,939 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-15 20:20:11,704 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
2019-08-15 20:50:25,927 INFO: Microblog startup [in /home/thevidvid/microblog/app/__init__.py:44]
